// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SpaceApi.Data;

#nullable disable

namespace neoHorizonApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609025023_InitialCreateDockerfile")]
    partial class InitialCreateDockerfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PredictionsMadeSpaceObject", b =>
                {
                    b.Property<int>("ObjectsInvolvedId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PredictionsId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ObjectsInvolvedId", "PredictionsId");

                    b.HasIndex("PredictionsId");

                    b.ToTable("PredictionsMadeSpaceObject");
                });

            modelBuilder.Entity("neoHorizonApi.Models.PredictionsMade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("IsGoingToCollide")
                        .HasColumnType("NUMBER(5)");

                    b.Property<long>("TimeUntilImpact")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("PredictionsMade");
                });

            modelBuilder.Entity("neoHorizonApi.Models.SpaceObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Radius")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("VelocityX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("VelocityY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("VelocityZ")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("X")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Y")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Z")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("SpaceObjects");
                });

            modelBuilder.Entity("PredictionsMadeSpaceObject", b =>
                {
                    b.HasOne("neoHorizonApi.Models.SpaceObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsInvolvedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("neoHorizonApi.Models.PredictionsMade", null)
                        .WithMany()
                        .HasForeignKey("PredictionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
